modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/pau101/Hat-Stands/issues"
[[mods]]
	modId="hatstands"
	version="${version}"
	displayName="Hat Stands"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/hat-stands"
	authors="pau101"
	description="Hat Stands for all your hat displaying needs."
	logoFile="logo.png"
[[dependencies.hatstands]]
	modId="forge"
	mandatory=true
	versionRange="[31.2,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.hatstands]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.15.2]"
	ordering="NONE"
	side="BOTH"
